### ISSUE TITLE
app building error

### ISSUE THREAD

**Issue by Sahil-pixel** [Android-for-Python/c4k_opencv_example#1]
File "/home/a/.local/lib/python3.6/site-packages/buildozer/targets/android.py", line 1350, in _update_libraries_references
    with io.open(project_fn, 'w', encoding='utf-8') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/a/c4k_opencv_example-main/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/c4k_opencv/project.properties'

**Comment by Android-for-Python** [comment]
No idea. Looks like some site specific issue building an aab. But that can't be correct because that would mean trying to monetize a free example. So I have no idea.
