### ISSUE TITLE
Does Camera Preview work on your phone?

### ISSUE THREAD

**Issue by zeroche72** [Android-for-Python/c4k_opencv_example#2]
I appreciate your information sharing.

I compiled your code with Google Colab.
Compiled successfully and created apk file.

However, when I ran it on my Android phone, it didn't run properly.
Is there anything else I need to check?

And if you can provide the apk file for android you made
I think it will help a lot.
Thank you again.

**Comment by Android-for-Python** [comment]
> However, when I ran it on my Android phone, it didn't run properly.
> Is there anything else I need to check?
General questions about using the Kivy tools should be addressed to the Kivy user groups.

> And if you can provide the apk file for android you made
No
